export enum ConfigKeys {
  DISCORD_LOGIN_REDIRECT = "DISCORD_LOGIN_REDIRECT",
  DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID",
  DISCORD_CLIENT_SECRET = "DISCORD_CLIENT_SECRET",
  DISCORD_CALLBACK_URL = "DISCORD_CALLBACK_URL",
  JWT_SECRET = "JWT_SECRET",
  DATABASE_URL = "DATABASE_URL",
}
