export enum ConfigKeys {
  DATABASE_URL = "DATABASE_URL",
  DISCORD_BOT_TOKEN = "DISCORD_BOT_TOKEN",
  DISCORD_CALLBACK_URL = "DISCORD_CALLBACK_URL",
  DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID",
  DISCORD_CLIENT_SECRET = "DISCORD_CLIENT_SECRET",
  DISCORD_LOGIN_SUCCESS_REDIRECT = "DISCORD_LOGIN_SUCCESS_REDIRECT",
  DISCORD_LOGIN_FAILURE_REDIRECT = "DISCORD_LOGIN_FAILURE_REDIRECT",
  JWT_SECRET = "JWT_SECRET",
}
